Fix Jenkinsfile post-merge

diff --git a/.ci/Jenkinsfile_coverage b/.ci/Jenkinsfile_coverage
--- a/.ci/Jenkinsfile_coverage
+++ b/.ci/Jenkinsfile_coverage
@@ -3,124 +3,118 @@
 library 'kibana-pipeline-library'
 kibanaLibrary.load() // load from the Jenkins instance
 
-stage("Kibana Pipeline") { // This stage is just here to help the BlueOcean UI a little bit
-  timeout(time: 180, unit: 'MINUTES') {
-    timestamps {
-      ansiColor('xterm') {
-        catchError {
-          withEnv([
-            'CODE_COVERAGE=1', // Needed for multiple ci scripts, such as remote.ts, test/scripts/*.sh, schema.js, etc.
-          ]) {
-            parallel([
-              'kibana-intake-agent': 'kibana-intake-agent': workers.intake('kibana-intake', './test/scripts/jenkins_unit.sh'),
-//              'x-pack-intake-agent': {
-//                withEnv([
-//                  'NODE_ENV=test' // Needed for jest tests only
-//                ]) {
-//                  workers.intake('x-pack-intake', './test/scripts/jenkins_xpack.sh')()
-//                }
-//              },
-              'kibana-oss-agent': workers.functional('kibana-oss-tests', { kibanaPipeline.buildOss() }, [
-                'oss-ciGroup1': kibanaPipeline.getOssCiGroupWorker(1),
-//                'oss-ciGroup2': kibanaPipeline.ossCiGroupProcess(2),
-//                'oss-ciGroup3': kibanaPipeline.ossCiGroupProcess(3),
-//                'oss-ciGroup4': kibanaPipeline.ossCiGroupProcess(4),
-//                'oss-ciGroup5': kibanaPipeline.ossCiGroupProcess(5),
-//                'oss-ciGroup6': kibanaPipeline.ossCiGroupProcess(6),
-//                'oss-ciGroup7': kibanaPipeline.ossCiGroupProcess(7),
-//                'oss-ciGroup8': kibanaPipeline.ossCiGroupProcess(8),
-//                'oss-ciGroup9': kibanaPipeline.ossCiGroupProcess(9),
-//                'oss-ciGroup10': kibanaPipeline.ossCiGroupProcess(10),
-//                'oss-ciGroup11': kibanaPipeline.ossCiGroupProcess(11),
-//                'oss-ciGroup12': kibanaPipeline.ossCiGroupProcess(12),
-              ]),
-//              'kibana-xpack-agent': workers.functional('kibana-xpack-tests', { kibanaPipeline.buildXpack() }, [
-//                'xpack-ciGroup1': kibanaPipeline.xpackCiGroupProcess(1),
-//                'xpack-ciGroup2': kibanaPipeline.xpackCiGroupProcess(2),
-//                'xpack-ciGroup3': kibanaPipeline.xpackCiGroupProcess(3),
-//                'xpack-ciGroup4': kibanaPipeline.xpackCiGroupProcess(4),
-//                'xpack-ciGroup5': kibanaPipeline.xpackCiGroupProcess(5),
-//                'xpack-ciGroup6': kibanaPipeline.xpackCiGroupProcess(6),
-//                'xpack-ciGroup7': kibanaPipeline.xpackCiGroupProcess(7),
-//                'xpack-ciGroup8': kibanaPipeline.xpackCiGroupProcess(8),
-//                'xpack-ciGroup9': kibanaPipeline.xpackCiGroupProcess(9),
-//                'xpack-ciGroup10': kibanaPipeline.xpackCiGroupProcess(10),
-//              ]),
-            ])
-            workers.base(name: 'coverage-worker', label: 'tests-l', ramDisk: false, bootstrapped: false) {
-              kibanaPipeline.downloadCoverageArtifacts()
+kibanaPipeline(timeoutMinutes: 180) {
+  catchErrors {
+    withEnv([
+      'CODE_COVERAGE=1', // Needed for multiple ci scripts, such as remote.ts, test/scripts/*.sh, schema.js, etc.
+    ]) {
+      parallel([
+        'kibana-intake-agent': 'kibana-intake-agent': workers.intake('kibana-intake', './test/scripts/jenkins_unit.sh'),
+        // 'x-pack-intake-agent': {
+        //   withEnv([
+        //     'NODE_ENV=test' // Needed for jest tests only
+        //   ]) {
+        //     workers.intake('x-pack-intake', './test/scripts/jenkins_xpack.sh')()
+        //   }
+        // },
+        'kibana-oss-agent': workers.functional('kibana-oss-tests', { kibanaPipeline.buildOss() }, [
+          'oss-ciGroup1': kibanaPipeline.getOssCiGroupWorker(1),
+          // 'oss-ciGroup2': kibanaPipeline.ossCiGroupProcess(2),
+          // 'oss-ciGroup3': kibanaPipeline.ossCiGroupProcess(3),
+          // 'oss-ciGroup4': kibanaPipeline.ossCiGroupProcess(4),
+          // 'oss-ciGroup5': kibanaPipeline.ossCiGroupProcess(5),
+          // 'oss-ciGroup6': kibanaPipeline.ossCiGroupProcess(6),
+          // 'oss-ciGroup7': kibanaPipeline.ossCiGroupProcess(7),
+          // 'oss-ciGroup8': kibanaPipeline.ossCiGroupProcess(8),
+          // 'oss-ciGroup9': kibanaPipeline.ossCiGroupProcess(9),
+          // 'oss-ciGroup10': kibanaPipeline.ossCiGroupProcess(10),
+          // 'oss-ciGroup11': kibanaPipeline.ossCiGroupProcess(11),
+          // 'oss-ciGroup12': kibanaPipeline.ossCiGroupProcess(12),
+        ]),
+        // 'kibana-xpack-agent': workers.functional('kibana-xpack-tests', { kibanaPipeline.buildXpack() }, [
+        //   'xpack-ciGroup1': kibanaPipeline.xpackCiGroupProcess(1),
+        //   'xpack-ciGroup2': kibanaPipeline.xpackCiGroupProcess(2),
+        //   'xpack-ciGroup3': kibanaPipeline.xpackCiGroupProcess(3),
+        //   'xpack-ciGroup4': kibanaPipeline.xpackCiGroupProcess(4),
+        //   'xpack-ciGroup5': kibanaPipeline.xpackCiGroupProcess(5),
+        //   'xpack-ciGroup6': kibanaPipeline.xpackCiGroupProcess(6),
+        //   'xpack-ciGroup7': kibanaPipeline.xpackCiGroupProcess(7),
+        //   'xpack-ciGroup8': kibanaPipeline.xpackCiGroupProcess(8),
+        //   'xpack-ciGroup9': kibanaPipeline.xpackCiGroupProcess(9),
+        //   'xpack-ciGroup10': kibanaPipeline.xpackCiGroupProcess(10),
+        // ]),
+      ])
+      workers.base(name: 'coverage-worker', label: 'tests-l', ramDisk: false, bootstrapped: false) {
+        kibanaPipeline.downloadCoverageArtifacts()
 
-              def timestamp = new Date(currentBuild.startTimeInMillis).format("yyyy-MM-dd'T'HH:mm:ss'Z'", TimeZone.getTimeZone("UTC"))
-              withEnv([
-                "TIME_STAMP=${timestamp}",
-                "LIVE_APP_PATH=live_cc_app"
-              ]) {
-                kibanaPipeline.bash(
-                  """
-                  source src/dev/ci_setup/setup_env.sh
+        def timestamp = new Date(currentBuild.startTimeInMillis).format("yyyy-MM-dd'T'HH:mm:ss'Z'", TimeZone.getTimeZone("UTC"))
+        withEnv([
+          "TIME_STAMP=${timestamp}",
+          "LIVE_APP_PATH=live_cc_app"
+        ]) {
+          kibanaPipeline.bash(
+            """
+            source src/dev/ci_setup/setup_env.sh
 
-                  # bootstrap from x-pack folder
-                  cd x-pack
-                  yarn kbn bootstrap --prefer-offline
+            # bootstrap from x-pack folder
+            cd x-pack
+            yarn kbn bootstrap --prefer-offline
 
-                  # Return to project root
-                  cd ..
+            # Return to project root
+            cd ..
 
-                  . src/dev/code_coverage/shell_scripts/extract_archives.sh
+            . src/dev/code_coverage/shell_scripts/extract_archives.sh
 
-                  . src/dev/code_coverage/shell_scripts/fix_html_reports_parallel.sh
+            . src/dev/code_coverage/shell_scripts/fix_html_reports_parallel.sh
 
-                  . src/dev/code_coverage/shell_scripts/merge_jest_and_functional.sh
+            . src/dev/code_coverage/shell_scripts/merge_jest_and_functional.sh
 
-                  . src/dev/code_coverage/shell_scripts/copy_mocha_reports.sh
+            . src/dev/code_coverage/shell_scripts/copy_mocha_reports.sh
 
-                  . src/dev/code_coverage/shell_scripts/ingest_coverage.sh ${BUILD_NUMBER} ${env.BUILD_URL}
+            . src/dev/code_coverage/shell_scripts/ingest_coverage.sh ${BUILD_NUMBER} ${env.BUILD_URL}
 
-                  # Bootstrap the CC App
-                  . src/dev/code_coverage/shell_scripts/query_app_initial_data.sh
+            # Bootstrap the CC App
+            . src/dev/code_coverage/shell_scripts/query_app_initial_data.sh
 
-                  # Check the bootstrapping
-                  cat ./bootstrapped.dat || echo "!!! bootstrapped.dat NOT FOUND?"
+            # Check the bootstrapping
+            cat ./bootstrapped.dat || echo "!!! bootstrapped.dat NOT FOUND?"
 
-                  # Populate the CC App with bootstrapped dat file
-                  node src/dev/code_coverage/node_scripts/populate_cc_app/index.js ./bootstrapped.dat src/dev/code_coverage/cc_app/public/initial_data.js
+            # Populate the CC App with bootstrapped dat file
+            node src/dev/code_coverage/node_scripts/populate_cc_app/index.js ./bootstrapped.dat src/dev/code_coverage/cc_app/public/initial_data.js
 
-                  # Check the population
-                  cat src/dev/code_coverage/cc_app/public/initial_data.js || echo "!!! initial_data.js NOT FOUND?"
+            # Check the population
+            cat src/dev/code_coverage/cc_app/public/initial_data.js || echo "!!! initial_data.js NOT FOUND?"
 
-                  # build cc app
-                  pushd src/dev/code_coverage/cc_app
-                  yarn
-                  yarn build:prod
-                  popd
+            # build cc app
+            pushd src/dev/code_coverage/cc_app
+            yarn
+            yarn build:prod
+            popd
 
-                  # copy built app over to it's final resting place :)
-                  cp -R src/dev/code_coverage/cc_app/build src/dev/code_coverage/live_cc_app
+            # copy built app over to it's final resting place :)
+            cp -R src/dev/code_coverage/cc_app/build src/dev/code_coverage/live_cc_app
 
-                """,
-                  "### Run `yarn kbn bootstrap && merge coverage` AND Ingest Code Coverage to ES Cluster AND Boot Coverage App"
-                )
-                kibanaPipeline.bash(
-                  """
-                  echo "### Canonical TIME_STAMP for the build and ingestion: ${TIME_STAMP}"
+          """,
+            "### Run `yarn kbn bootstrap && merge coverage` AND Ingest Code Coverage to ES Cluster AND Boot Coverage App"
+          )
+          kibanaPipeline.bash(
+            """
+            echo "### Canonical TIME_STAMP for the build and ingestion: ${TIME_STAMP}"
 
-                  """,
-                  "### About to Upload Code Coverage Static Site"
-                )
-                kibanaCoverage.uploadCoverageStaticSite(TIME_STAMP, LIVE_APP_PATH)
-              }
-
-              sh 'tar -czf kibana-jest-coverage.tar.gz target/kibana-coverage/jest-combined/*'
-              kibanaPipeline.uploadCoverageArtifacts("coverage/jest-combined", 'kibana-jest-coverage.tar.gz')
-              sh 'tar -czf kibana-functional-coverage.tar.gz target/kibana-coverage/functional-combined/*'
-              kibanaPipeline.uploadCoverageArtifacts("coverage/functional-combined", 'kibana-functional-coverage.tar.gz')
-              sh 'tar -czf kibana-mocha-coverage.tar.gz target/kibana-coverage/mocha-combined/*'
-              kibanaPipeline.uploadCoverageArtifacts("coverage/mocha-combined", 'kibana-mocha-coverage.tar.gz')
-            }
-          }
+            """,
+            "### About to Upload Code Coverage Static Site"
+          )
+          kibanaCoverage.uploadCoverageStaticSite(TIME_STAMP, LIVE_APP_PATH)
         }
-        kibanaPipeline.sendMail()
+
+        sh 'tar -czf kibana-jest-coverage.tar.gz target/kibana-coverage/jest-combined/*'
+        kibanaPipeline.uploadCoverageArtifacts("coverage/jest-combined", 'kibana-jest-coverage.tar.gz')
+        sh 'tar -czf kibana-functional-coverage.tar.gz target/kibana-coverage/functional-combined/*'
+        kibanaPipeline.uploadCoverageArtifacts("coverage/functional-combined", 'kibana-functional-coverage.tar.gz')
+        sh 'tar -czf kibana-mocha-coverage.tar.gz target/kibana-coverage/mocha-combined/*'
+        kibanaPipeline.uploadCoverageArtifacts("coverage/mocha-combined", 'kibana-mocha-coverage.tar.gz')
       }
     }
   }
+  kibanaPipeline.sendMail()
 }
