Move the ingestion up one, and export the time stamp (utc-ified).

diff --git a/.ci/Jenkinsfile_coverage b/.ci/Jenkinsfile_coverage
--- a/.ci/Jenkinsfile_coverage
+++ b/.ci/Jenkinsfile_coverage
@@ -61,6 +61,19 @@ stage("Kibana Pipeline") { // This stage is just here to help the BlueOcean UI a
             kibanaPipeline.jobRunner('tests-l', false) {
               kibanaPipeline.downloadCoverageArtifacts()
               kibanaPipeline.bash(
+                """
+                  echo "###  Ingesting Code Coverage"
+                  source src/dev/ci_setup/setup_env.sh
+                  export ES_HOST=https://super:changeme@87883974a2984732b6cb134e5c7e240f.us-east-1.aws.staging.foundit.no:9243
+                  export BUILD_ID=${BUILD_NUMBER}
+                  export TIME_STAMP=\$(date -u +%FT%T)
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/jest-combined/coverage-summary.json || echo "### target/kibana-coverage/jest-combined/coverage-summary.json not found?"
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/functional-combined/coverage-summary.json || echo "### target/kibana-coverage/functional-combined/coverage-summary.json not found?"
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/mocha-combined/coverage-summary.json || echo "### target/kibana-coverage/mocha-combined/coverage-summary.json not found?" 
+                """,
+                "Ingest Code Coverage to ES Cluster"
+              )
+              kibanaPipeline.bash(
                 '''
                   # bootstrap from x-pack folder
                   source src/dev/ci_setup/setup_env.sh
@@ -95,19 +108,6 @@ stage("Kibana Pipeline") { // This stage is just here to help the BlueOcean UI a
                   cp -r /tmp/extracted_coverage/target/kibana-coverage/mocha target/kibana-coverage/mocha-combined
                 ''',
                 "run `yarn kbn bootstrap && merge coverage`"
-              )
-              kibanaPipeline.bash(
-                """
-                  # ingest code coverage
-                  echo "###  Ingesting Code Coverage"
-                  export ES_HOST=https://super:changeme@87883974a2984732b6cb134e5c7e240f.us-east-1.aws.staging.foundit.no:9243
-                  export BUILD_ID=${BUILD_NUMBER}
-                  # export TIME_STAMP=${}
-                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/jest-combined/coverage-summary.json || echo "### target/kibana-coverage/jest-combined/coverage-summary.json not found?"
-                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/functional-combined/coverage-summary.json || echo "### target/kibana-coverage/functional-combined/coverage-summary.json not found?"
-                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/mocha-combined/coverage-summary.json || echo "### target/kibana-coverage/mocha-combined/coverage-summary.json not found?" 
-                """,
-                "Ingest Code Coverage to ES Cluster"
               )
               sh 'tar -czf kibana-jest-coverage.tar.gz target/kibana-coverage/jest-combined/*'
               kibanaPipeline.uploadCoverageArtifacts("coverage/jest-combined", 'kibana-jest-coverage.tar.gz')
