Ok, so that worked; Now just fail

diff --git a/.ci/Jenkinsfile_coverage b/.ci/Jenkinsfile_coverage
--- a/.ci/Jenkinsfile_coverage
+++ b/.ci/Jenkinsfile_coverage
@@ -134,14 +134,17 @@ def maybeFailFast() {
       withVaultSecret(secret: vaultSecret, secret_field: 'password', variable_name: 'PASS_FROM_VAULT') {
         kibanaPipeline.bash(
           """
-              source src/dev/ci_setup/setup_env.sh
-
-              if [ -n "${VAULT_ADDR}" ] && [ -n "${USER_FROM_VAULT}" ] && [ -n "${PASS_FROM_VAULT}" ] && [ -n "${HOST_FROM_VAULT}" ]; then
-                echo "### Vault variables are DEFINED"
-              else
-                echo "### 1 or more Vault variables are undefined"
+                set -x
+                echo "### Failing on purpose"
                 exit 1
-              fi
+//              source src/dev/ci_setup/setup_env.sh
+//
+//              if [ -n "${VAULT_ADDR}" ] && [ -n "${USER_FROM_VAULT}" ] && [ -n "${PASS_FROM_VAULT}" ] && [ -n "${HOST_FROM_VAULT}" ]; then
+//                echo "### Vault variables are DEFINED"
+//              else
+//                echo "### 1 or more Vault variables are undefined"
+//                exit 1
+//              fi
 
               """, "### Fail fast without vault"
         )
