Refactor the ingestion back into the merge code, add escapes where I think they are needed.

diff --git a/.ci/Jenkinsfile_coverage b/.ci/Jenkinsfile_coverage
--- a/.ci/Jenkinsfile_coverage
+++ b/.ci/Jenkinsfile_coverage
@@ -63,20 +63,6 @@ stage("Kibana Pipeline") { // This stage is just here to help the BlueOcean UI a
               kibanaPipeline.uploadCoverageStaticSite(new Date().format("yyyy-MM-dd'T'HH-mm-ss'Z'", TimeZone.getTimeZone("UTC")))
               kibanaPipeline.bash(
                 """
-                  echo "###  Ingesting Code Coverage"
-                  source src/dev/ci_setup/setup_env.sh
-                  yarn kbn bootstrap --prefer-offline
-                  export ES_HOST=https://super:changeme@87883974a2984732b6cb134e5c7e240f.us-east-1.aws.staging.foundit.no:9243
-                  export BUILD_ID=${BUILD_NUMBER}
-                  export TIME_STAMP=\$(date -u +%FT%T)
-                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/jest-combined/coverage-summary.json || echo "### target/kibana-coverage/jest-combined/coverage-summary.json not found?"
-                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/functional-combined/coverage-summary.json || echo "### target/kibana-coverage/functional-combined/coverage-summary.json not found?"
-                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/mocha-combined/coverage-summary.json || echo "### target/kibana-coverage/mocha-combined/coverage-summary.json not found?"
-                """,
-                "Ingest Code Coverage to ES Cluster"
-              )
-              kibanaPipeline.bash(
-                '''
                   # bootstrap from x-pack folder
                   source src/dev/ci_setup/setup_env.sh
                   cd x-pack
@@ -94,13 +80,22 @@ stage("Kibana Pipeline") { // This stage is just here to help the BlueOcean UI a
                     tar -xzf /tmp/downloaded_coverage/coverage/kibana-xpack-tests-${i}/kibana-coverage.tar.gz -C /tmp/extracted_coverage
                   done
                   # replace path in json files to have valid html report
-                  pwd=$(pwd)
+                  pwd=\$(pwd)
                   du -sh /tmp/extracted_coverage/target/kibana-coverage/
                   echo replacing path in json files
                   for i in {1..9}; do
-                    sed -i "s|/dev/shm/workspace/kibana|$pwd|g" /tmp/extracted_coverage/target/kibana-coverage/functional/${i}*.json &
+                    sed -i "s|/dev/shm/workspace/kibana|\$pwd|g" /tmp/extracted_coverage/target/kibana-coverage/functional/${i}*.json &
                   done
                   wait
+
+                  echo "###  Ingesting Code Coverage"
+                  export ES_HOST=https://super:changeme@87883974a2984732b6cb134e5c7e240f.us-east-1.aws.staging.foundit.no:9243
+                  export BUILD_ID=${BUILD_NUMBER}
+                  export TIME_STAMP=\$(date -u +%FT%T)
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/jest-combined/coverage-summary.json || echo "### target/kibana-coverage/jest-combined/coverage-summary.json not found?"
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/functional-combined/coverage-summary.json || echo "### target/kibana-coverage/functional-combined/coverage-summary.json not found?"
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/mocha-combined/coverage-summary.json || echo "### target/kibana-coverage/mocha-combined/coverage-summary.json not found?"
+
                   # merge oss & x-pack reports
                   echo merging coverage reports
                   yarn nyc report --temp-dir /tmp/extracted_coverage/target/kibana-coverage/jest --report-dir target/kibana-coverage/jest-combined --reporter=html --reporter=json-summary
@@ -108,8 +103,8 @@ stage("Kibana Pipeline") { // This stage is just here to help the BlueOcean UI a
                   echo copy mocha reports
                   mkdir -p target/kibana-coverage/mocha-combined
                   cp -r /tmp/extracted_coverage/target/kibana-coverage/mocha target/kibana-coverage/mocha-combined
-                ''',
-                "run `yarn kbn bootstrap && merge coverage`"
+                """,
+                "Ingest Code Coverage to ES Cluster and Run `yarn kbn bootstrap && merge coverage`"
               )
               sh 'tar -czf kibana-jest-coverage.tar.gz target/kibana-coverage/jest-combined/*'
               kibanaPipeline.uploadCoverageArtifacts("coverage/jest-combined", 'kibana-jest-coverage.tar.gz')
