Run some from both distros

diff --git a/.ci/Jenkinsfile_coverage b/.ci/Jenkinsfile_coverage
--- a/.ci/Jenkinsfile_coverage
+++ b/.ci/Jenkinsfile_coverage
@@ -13,26 +13,27 @@ kibanaPipeline(timeoutMinutes: 180) {
       workers.base(name: 'coverage-worker', label: 'tests-l', ramDisk: false, bootstrapped: false) {
         maybeFailFast()
       }
-//      parallel([
-//        'kibana-intake-agent': workers.intake('kibana-intake', './test/scripts/jenkins_unit.sh'),
-//        'x-pack-intake-agent': {
-//          withEnv([
-//            'NODE_ENV=test' // Needed for jest tests only
-//          ]) {
-//            workers.intake('x-pack-intake', './test/scripts/jenkins_xpack.sh')()
-//          }
-//        },
-//        'kibana-oss-agent'   : workers.functional(
-//          'kibana-oss-tests',
-//          { kibanaPipeline.buildOss() },
-//          ossProks()
-//        ),
-//        'kibana-xpack-agent' : workers.functional(
-//          'kibana-xpack-tests',
-//          { kibanaPipeline.buildXpack() },
-//          xpackProks()
-//        ),
-//      ])
+
+      parallel([
+        'kibana-intake-agent': workers.intake('kibana-intake', './test/scripts/jenkins_unit.sh'),
+        'x-pack-intake-agent': {
+          withEnv([
+            'NODE_ENV=test' // Needed for jest tests only
+          ]) {
+            workers.intake('x-pack-intake', './test/scripts/jenkins_xpack.sh')()
+          }
+        },
+        'kibana-oss-agent'   : workers.functional(
+          'kibana-oss-tests',
+          { kibanaPipeline.buildOss() },
+          ossProks()
+        ),
+        'kibana-xpack-agent' : workers.functional(
+          'kibana-xpack-tests',
+          { kibanaPipeline.buildXpack() },
+          xpackProks()
+        ),
+      ])
 
 
       workers.base(name: 'coverage-worker', label: 'tests-l', ramDisk: false, bootstrapped: false) {
@@ -45,46 +46,46 @@ kibanaPipeline(timeoutMinutes: 180) {
           "QA_TEAM_ROCKS=true"
         ]) {
 
-//          def vaultSecret = 'secret/kibana-issues/prod/coverage/elasticsearch'
-//          withVaultSecret(secret: vaultSecret, secret_field: 'host', variable_name: 'HOST_FROM_VAULT') {
-//            withVaultSecret(secret: vaultSecret, secret_field: 'username', variable_name: 'USER_FROM_VAULT') {
-//              withVaultSecret(secret: vaultSecret, secret_field: 'password', variable_name: 'PASS_FROM_VAULT') {
-//                kibanaPipeline.bash(
-//                  """
-//                  source src/dev/ci_setup/setup_env.sh
-//
-//                  # bootstrap from x-pack folder
-//                  cd x-pack
-//                  yarn kbn bootstrap --prefer-offline
-//
-//                  # Return to project root
-//                  cd ..
-//
-//                  . src/dev/code_coverage/shell_scripts/extract_archives.sh
-//
-//                  . src/dev/code_coverage/shell_scripts/fix_html_reports_parallel.sh
-//
-//                  . src/dev/code_coverage/shell_scripts/merge_jest_and_functional.sh
-//
-//                  . src/dev/code_coverage/shell_scripts/copy_mocha_reports.sh
-//
-//                  . src/dev/code_coverage/shell_scripts/ingest_coverage.sh ${BUILD_NUMBER} ${env.BUILD_URL}
-//
-//                """, "### Bootstrap shell and kibana env, merge and ingest code coverage"
-//                )
-//              }
-//            }
-//          }
-//          kibanaPipeline.bash(
-//            """
-//            echo "### Canonical TIME_STAMP for the build and ingestion: ${TIME_STAMP}"
-//
-//            """,
-//            "### About to Upload Code Coverage Static Site"
-//          )
-//          kibanaCoverage.uploadCoverageStaticSite(TIME_STAMP)
-        }
+          def vaultSecret = 'secret/kibana-issues/prod/coverage/elasticsearch'
+          withVaultSecret(secret: vaultSecret, secret_field: 'host', variable_name: 'HOST_FROM_VAULT') {
+            withVaultSecret(secret: vaultSecret, secret_field: 'username', variable_name: 'USER_FROM_VAULT') {
+              withVaultSecret(secret: vaultSecret, secret_field: 'password', variable_name: 'PASS_FROM_VAULT') {
+                kibanaPipeline.bash(
+                  """
+                  source src/dev/ci_setup/setup_env.sh
 
+                  # bootstrap from x-pack folder
+                  cd x-pack
+                  yarn kbn bootstrap --prefer-offline
+
+                  # Return to project root
+                  cd ..
+
+                  . src/dev/code_coverage/shell_scripts/extract_archives.sh
+
+                  . src/dev/code_coverage/shell_scripts/fix_html_reports_parallel.sh
+
+                  . src/dev/code_coverage/shell_scripts/merge_jest_and_functional.sh
+
+                  . src/dev/code_coverage/shell_scripts/copy_mocha_reports.sh
+
+                  . src/dev/code_coverage/shell_scripts/ingest_coverage.sh ${BUILD_NUMBER} ${env.BUILD_URL}
+
+                """, "### Bootstrap shell and kibana env, merge and ingest code coverage"
+                )
+              }
+            }
+          }
+          kibanaPipeline.bash(
+            """
+            echo "### Canonical TIME_STAMP for the build and ingestion: ${TIME_STAMP}"
+
+            """,
+            "### About to Upload Code Coverage Static Site"
+          )
+          kibanaCoverage.uploadCoverageStaticSite(TIME_STAMP)
+        }
+//        TODO-TRE UNCOMMENT
 //        sh 'tar -czf kibana-jest-coverage.tar.gz target/kibana-coverage/jest-combined/*'
 //        kibanaPipeline.uploadCoverageArtifacts("coverage/jest-combined", 'kibana-jest-coverage.tar.gz')
 //        sh 'tar -czf kibana-functional-coverage.tar.gz target/kibana-coverage/functional-combined/*'
@@ -103,15 +104,15 @@ def ossProks() {
     'oss-ciGroup1': kibanaPipeline.ossCiGroupProcess(1),
     'oss-ciGroup2': kibanaPipeline.ossCiGroupProcess(2),
     'oss-ciGroup3': kibanaPipeline.ossCiGroupProcess(3),
-    'oss-ciGroup4': kibanaPipeline.ossCiGroupProcess(4),
-    'oss-ciGroup5': kibanaPipeline.ossCiGroupProcess(5),
-    'oss-ciGroup6': kibanaPipeline.ossCiGroupProcess(6),
-    'oss-ciGroup7': kibanaPipeline.ossCiGroupProcess(7),
-    'oss-ciGroup8': kibanaPipeline.ossCiGroupProcess(8),
-    'oss-ciGroup9': kibanaPipeline.ossCiGroupProcess(9),
-    'oss-ciGroup10': kibanaPipeline.ossCiGroupProcess(10),
-    'oss-ciGroup11': kibanaPipeline.ossCiGroupProcess(11),
-    'oss-ciGroup12': kibanaPipeline.ossCiGroupProcess(12),
+//    'oss-ciGroup4': kibanaPipeline.ossCiGroupProcess(4),
+//    'oss-ciGroup5': kibanaPipeline.ossCiGroupProcess(5),
+//    'oss-ciGroup6': kibanaPipeline.ossCiGroupProcess(6),
+//    'oss-ciGroup7': kibanaPipeline.ossCiGroupProcess(7),
+//    'oss-ciGroup8': kibanaPipeline.ossCiGroupProcess(8),
+//    'oss-ciGroup9': kibanaPipeline.ossCiGroupProcess(9),
+//    'oss-ciGroup10': kibanaPipeline.ossCiGroupProcess(10),
+//    'oss-ciGroup11': kibanaPipeline.ossCiGroupProcess(11),
+//    'oss-ciGroup12': kibanaPipeline.ossCiGroupProcess(12),
   ]
 }
 
@@ -120,13 +121,13 @@ def xpackProks() {
     'xpack-ciGroup1' : kibanaPipeline.xpackCiGroupProcess(1),
     'xpack-ciGroup2' : kibanaPipeline.xpackCiGroupProcess(2),
     'xpack-ciGroup3' : kibanaPipeline.xpackCiGroupProcess(3),
-    'xpack-ciGroup4' : kibanaPipeline.xpackCiGroupProcess(4),
-    'xpack-ciGroup5' : kibanaPipeline.xpackCiGroupProcess(5),
-    'xpack-ciGroup6' : kibanaPipeline.xpackCiGroupProcess(6),
-    'xpack-ciGroup7' : kibanaPipeline.xpackCiGroupProcess(7),
-    'xpack-ciGroup8' : kibanaPipeline.xpackCiGroupProcess(8),
-    'xpack-ciGroup9' : kibanaPipeline.xpackCiGroupProcess(9),
-    'xpack-ciGroup10': kibanaPipeline.xpackCiGroupProcess(10),
+//    'xpack-ciGroup4' : kibanaPipeline.xpackCiGroupProcess(4),
+//    'xpack-ciGroup5' : kibanaPipeline.xpackCiGroupProcess(5),
+//    'xpack-ciGroup6' : kibanaPipeline.xpackCiGroupProcess(6),
+//    'xpack-ciGroup7' : kibanaPipeline.xpackCiGroupProcess(7),
+//    'xpack-ciGroup8' : kibanaPipeline.xpackCiGroupProcess(8),
+//    'xpack-ciGroup9' : kibanaPipeline.xpackCiGroupProcess(9),
+//    'xpack-ciGroup10': kibanaPipeline.xpackCiGroupProcess(10),
   ]
 }
 
@@ -138,19 +139,16 @@ def maybeFailFast() {
       withVaultSecret(secret: vaultSecret, secret_field: 'password', variable_name: 'PASS_FROM_VAULT') {
         kibanaPipeline.bash(
           """
-                set -x
-                echo "### Failing on purpose"
-                exit 1
-//              source src/dev/ci_setup/setup_env.sh
-//
-//              if [ -n "${VAULT_ADDR}" ] && [ -n "${USER_FROM_VAULT}" ] && [ -n "${PASS_FROM_VAULT}" ] && [ -n "${HOST_FROM_VAULT}" ]; then
-//                echo "### Vault variables are DEFINED"
-//              else
-//                echo "### 1 or more Vault variables are undefined"
-//                exit 1
-//              fi
+              source src/dev/ci_setup/setup_env.sh
 
-              """, "### Fail fast without vault"
+              if [ -n "${VAULT_ADDR}" ] && [ -n "${USER_FROM_VAULT}" ] && [ -n "${PASS_FROM_VAULT}" ] && [ -n "${HOST_FROM_VAULT}" ]; then
+                echo "### Vault variables are DEFINED"
+              else
+                echo "### 1 or more Vault variables are undefined"
+                exit 1
+              fi
+
+              """, "### Fail fast without Vault Env Variables"
         )
       }
     }
