Export env vars to remove duplication. Also, update prefix to reflect what I think the static site's url will look like.

diff --git a/.ci/Jenkinsfile_coverage b/.ci/Jenkinsfile_coverage
--- a/.ci/Jenkinsfile_coverage
+++ b/.ci/Jenkinsfile_coverage
@@ -97,13 +97,15 @@ stage("Kibana Pipeline") { // This stage is just here to help the BlueOcean UI a
                 "run `yarn kbn bootstrap && merge coverage`"
               )
               kibanaPipeline.bash(
-                '''
+                """
                   # ingest code coverage
                   echo "###  Ingesting Code Coverage"
-                  ES_HOST=https://super:changeme@87883974a2984732b6cb134e5c7e240f.us-east-1.aws.staging.foundit.no:9243 node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/jest-combined/coverage-summary.json || echo "### target/kibana-coverage/jest-combined/coverage-summary.json not found?"
-                  ES_HOST=https://super:changeme@87883974a2984732b6cb134e5c7e240f.us-east-1.aws.staging.foundit.no:9243 node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/functional-combined/coverage-summary.json || echo "### target/kibana-coverage/functional-combined/coverage-summary.json not found?"
-                  ES_HOST=https://super:changeme@87883974a2984732b6cb134e5c7e240f.us-east-1.aws.staging.foundit.no:9243 node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/mocha-combined/coverage-summary.json || echo "### target/kibana-coverage/mocha-combined/coverage-summary.json not found?" 
-                ''',
+                  export ES_HOST=https://super:changeme@87883974a2984732b6cb134e5c7e240f.us-east-1.aws.staging.foundit.no:9243
+                  export BUILD_ID=${BUILD_NUMBER}
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/jest-combined/coverage-summary.json || echo "### target/kibana-coverage/jest-combined/coverage-summary.json not found?"
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/functional-combined/coverage-summary.json || echo "### target/kibana-coverage/functional-combined/coverage-summary.json not found?"
+                  node scripts/convert_and_send_json_summary.js --verbose --path target/kibana-coverage/mocha-combined/coverage-summary.json || echo "### target/kibana-coverage/mocha-combined/coverage-summary.json not found?" 
+                """,
                 "Ingest Code Coverage to ES Cluster"
               )
               sh 'tar -czf kibana-jest-coverage.tar.gz target/kibana-coverage/jest-combined/*'
