[build/serverless] Add support for jemalloc
Adds support for enabling jemalloc behind the KBN_ENABLE_JEMALLOC flag
on serverless projects.

diff --git a/src/dev/build/tasks/bin/scripts/kibana b/src/dev/build/tasks/bin/scripts/kibana
--- a/src/dev/build/tasks/bin/scripts/kibana
+++ b/src/dev/build/tasks/bin/scripts/kibana
@@ -38,6 +38,13 @@ fi
 if [ "$KBN_ENABLE_POINTER_COMPRESSION" = 'true' ]; then
   NODE="${DIR}/node/pointer-compression/bin/node"
 fi
+if [ "$KBN_ENABLE_JEMALLOC" = 'true' ]; then
+  export LD_PRELOAD='/usr/lib/libjemalloc.so.2'
+  if [ ! -f "$LD_PRELOAD" ]; then
+    echo "unable to find jemalloc"
+    exit 1
+  fi
+fi
 {{/serverless}}
 {{#forcePointerCompression}}
 NODE="${DIR}/node/pointer-compression/bin/node"
