chore(NA): run microdnf update inside a retry

diff --git a/src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile b/src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile
--- a/src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile
+++ b/src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile
@@ -51,7 +51,12 @@ EXPOSE 5601
   RUN printf "[main]\nexclude=crypto-policies" >  /etc/dnf/dnf.conf
 
   # update microdnf to have exclusion feature for dnf configuration
-  {{packageManager}} update microdnf --setopt=tsflags=nodocs -y
+  RUN for iter in {1..10}; do \
+        {{packageManager}} update microdnf --setopt=tsflags=nodocs -y && \
+        {{packageManager}} clean all && exit_code=0 && break || exit_code=$? && echo "{{packageManager}} error: retry $iter in 10s" && \
+        sleep 10; \
+      done; \
+      (exit $exit_code)
 {{/ubi}}
 
 RUN for iter in {1..10}; do \
