[Build] Add flag to revert to glibc 2.42 memory management (#255699)
## Summary

Reverts #255691

Newer Chainguard images updated to `glibc 2.43` which changes memory
allocation behavior. Adding this flag reverts that behavior and allows
us to unblock Chainguard image updates.

See
https://groups.google.com/a/elastic.co/g/support_team/c/RBgzGXEdyR8/m/MxtQhaAmCQAJ
for more details.

(cherry picked from commit 9f346df20cdb34f0792201cd70a5274a8f03995d)

# Conflicts:
#	src/dev/build/tasks/os_packages/docker_generator/run.ts
#	src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile

diff --git a/src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile b/src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile
--- a/src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile
+++ b/src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile
@@ -92,8 +92,15 @@ RUN microdnf install --setopt=tsflags=nodocs -y \
       microdnf clean all
 {{/ubi}}
 {{#wolfi}}
-# TODO: Remove pinned shadow version once Wolfi image is updated. Newer releases of shadow require glibc 2.43 which is not available in the current image SHA.
-RUN apk --no-cache add bash curl fontconfig font-liberation libstdc++ libnss findutils shadow=4.19.3-r0 ca-certificates
+# Wolfi updated glibc from 2.42 to 2.43, which changed memory allocation behavior. This flag disables the new behavior.
+ENV GLIBC_TUNABLES=glibc.malloc.hugetlb=0
+
+RUN for iter in 1 2 3 4 5; do \
+      apk --no-cache add bash curl fontconfig font-liberation libstdc++ libnss findutils shadow ca-certificates{{#serverless}} libjemalloc2 mimalloc2{{/serverless}} && break; \
+      echo "apk add failed (attempt $iter/5), retrying in $((iter * 10))s..."; \
+      sleep $((iter * 10)); \
+      [ $iter -eq 5 ] && exit 1; \
+    done
 {{/wolfi}}
 
 # Bring in Kibana from the initial stage.
