cleanup

diff --git a/src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile b/src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile
--- a/src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile
+++ b/src/dev/build/tasks/os_packages/docker_generator/templates/base/Dockerfile
@@ -12,10 +12,10 @@
 FROM {{{baseImageName}}} AS builder
 
 {{#ubi}}
-RUN {{packageManager}} install -y findutils tar gzip
+RUN microdnf install -y findutils tar gzip
 {{/ubi}}
 {{#ubuntu}}
-RUN {{packageManager}} update && DEBIAN_FRONTEND=noninteractive {{packageManager}} install -y curl
+RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl
 {{/ubuntu}}
 {{#chainguard}}
 RUN apk --no-cache add curl
@@ -68,10 +68,10 @@ EXPOSE 5601
 
 {{#ubi}}
 RUN for iter in {1..10}; do \
-      {{packageManager}} update --setopt=tsflags=nodocs -y && \
-      {{packageManager}} install --setopt=tsflags=nodocs -y \
+      microdnf update --setopt=tsflags=nodocs -y && \
+      microdnf install --setopt=tsflags=nodocs -y \
         fontconfig freetype shadow-utils nss findutils {{#fips}}perl make gcc tar {{/fips}}&& \
-      {{packageManager}} clean all && exit_code=0 && break || exit_code=$? && echo "{{packageManager}} error: retry $iter in 10s" && \
+      microdnf clean all && exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && \
       sleep 10; \
     done; \
     (exit $exit_code)
@@ -79,20 +79,18 @@ RUN for iter in {1..10}; do \
 {{#ubuntu}}
 RUN for iter in {1..10}; do \
       export DEBIAN_FRONTEND=noninteractive && \
-      {{packageManager}} update  && \
-      {{packageManager}} upgrade -y  && \
-      {{packageManager}} install -y --no-install-recommends \
+      apt-get update  && \
+      apt-get upgrade -y  && \
+      apt-get install -y --no-install-recommends \
        fontconfig fonts-liberation libnss3 libfontconfig1 ca-certificates curl && \
-      {{packageManager}} clean && \
-      rm -rf /var/lib/apt/lists/* && exit_code=0 && break || exit_code=$? && echo "{{packageManager}} error: retry $iter in 10s" && \
+      apt-get clean && \
+      rm -rf /var/lib/apt/lists/* && exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && \
       sleep 10; \
     done; \
     (exit $exit_code)
 {{/ubuntu}}
 {{#chainguard}}
-RUN apk update && \
-  apk --no-cache upgrade && \
-  apk --no-cache add bash curl fontconfig libstdc++ freetype nss findutils shadow
+RUN apk --no-cache add bash curl fontconfig libstdc++ freetype nss findutils shadow
 {{/chainguard}}
 
 # Add an init process, check the checksum to make sure it's a match
